/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE GET_WIFI_STATUS PACKING
package com.MAVLink.quad_java.common;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
* Request the current status of the WiFi Access point.
*/
public class msg_get_wifi_status extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_GET_WIFI_STATUS = 154;
    public static final int MAVLINK_MSG_LENGTH = 6;
    private static final long serialVersionUID = MAVLINK_MSG_ID_GET_WIFI_STATUS;


      
    /**
    * MAC Address of the Wireless Access Point (In case we ever have more than one access point)
    */
    public byte bssid[] = new byte[6];
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket();
        packet.len = MAVLINK_MSG_LENGTH;
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_GET_WIFI_STATUS;
              
        
        for (int i = 0; i < bssid.length; i++) {
            packet.payload.putByte(bssid[i]);
        }
                    
        
        return packet;
    }

    /**
    * Decode a get_wifi_status message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
         
        for (int i = 0; i < this.bssid.length; i++) {
            this.bssid[i] = payload.getByte();
        }
                
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_get_wifi_status(){
        msgid = MAVLINK_MSG_ID_GET_WIFI_STATUS;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_get_wifi_status(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_GET_WIFI_STATUS;
        unpack(mavLinkPacket.payload);        
    }

     
    /**
    * Sets the buffer of this message with a string, adds the necessary padding
    */
    public void setBssid(String str) {
        int len = Math.min(str.length(), 6);
        for (int i=0; i<len; i++) {
            bssid[i] = (byte) str.charAt(i);
        }

        for (int i=len; i<6; i++) {            // padding for the rest of the buffer
            bssid[i] = 0;
        }
    }

    /**
    * Gets the message, formated as a string
    */
    public String getBssid() {
        String result = "";
        for (int i = 0; i < 6; i++) {
            if (bssid[i] != 0)
                result = result + (char) bssid[i];
            else
                break;
        }
        return result;

    }
                         
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_GET_WIFI_STATUS -"+" bssid:"+bssid+"";
    }
}
        